package pit:javy-guest@0.1.0;

world pit-javy-guest {
    export compile-src: func(src: list<u8>) -> result<list<u8>, string>;
    export initialize-runtime: func();
    export invoke: func(bytecode: list<u8>, function: option<string>);
    import pit-call: func(value: u32) -> u32;
}
