[package]
name = "pit-wasmtime-executor"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3.34"
napi = { version = "3.14.2", default-features = false, features = ["async", "napi8"] }
napi-derive = "3.6.12"
wasmtime = "49.0.2"
wasmtime-wasi = "49.0.2"

[build-dependencies]
napi-build = "2.6.0"

[profile.release]
codegen-units = 1
lto = "thin"
strip = "symbols"
