[package]
name = "pit-wasmtime-executor"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3.34"
napi = { version = "3.13.0", default-features = false, features = ["async", "napi8"] }
napi-derive = "3.6.9"
wasmtime = "49.0.1"
wasmtime-wasi = "49.0.1"

[build-dependencies]
napi-build = "2.5.0"

[profile.release]
codegen-units = 1
lto = "thin"
strip = "symbols"
