import { readFileSync } from "node:fs";

import { globalFunctionGroups } from "./globals.js";

// The preamble is a real declaration file, so backticks and ${...} in it need no escaping and
// the formatter and linter treat it as code. tsconfig.json excludes it: the generated contract
// already declares the same global types for Pit's own compile.
const GLOBAL_CONTRACT_PREAMBLE = readFileSync(
  new URL("./global-contract-preamble.d.ts", import.meta.url),
  "utf8",
).trimEnd();

function interfaceName(namespace: string): string {
  return namespace === "functions"
    ? "PitFunctionControls"
    : `Pit${namespace.charAt(0).toUpperCase()}${namespace.slice(1)}Functions`;
}

function indentDeclaration(declaration: string): string {
  return declaration
    .split("\n")
    .map((line) => `  ${line}`)
    .join("\n");
}

export function generateGlobalContract(): string {
  const groups = [...globalFunctionGroups()];
  const interfaces = groups
    .map(([name, definitions]) => {
      const methods = definitions
        .map((definition) => indentDeclaration(definition.declaration))
        .join("\n\n");
      return `interface ${interfaceName(name)} {\n${methods}\n}`;
    })
    .join("\n\n");
  const dependencies = groups.map(([name]) => `  ${name}: ${interfaceName(name)};`).join("\n");
  return `// Generated by scripts/generate-global-contract.ts. Do not edit.\n\n${GLOBAL_CONTRACT_PREAMBLE}\n\n${interfaces}\n\ninterface PitDependencies {\n${dependencies}\n}\n\ntype PitSavedInput<T extends (...args: any[]) => any> =\n  Parameters<T> extends [any, ...infer Rest] ? Rest[0] : undefined;\n\ntype PitProgram = (\n  dependencies: PitDependencies,\n  input?: any,\n) => PitResult | void | Promise<PitResult | void>;\n`;
}
